INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_LIMESDRMOD limesdrmod)

FIND_PATH(
    LIMESDRMOD_INCLUDE_DIRS
    NAMES limesdrmod/api.h
    HINTS $ENV{LIMESDRMOD_DIR}/include
        ${PC_LIMESDRMOD_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    LIMESDRMOD_LIBRARIES
    NAMES gnuradio-limesdrmod
    HINTS $ENV{LIMESDRMOD_DIR}/lib
        ${PC_LIMESDRMOD_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIMESDRMOD DEFAULT_MSG LIMESDRMOD_LIBRARIES LIMESDRMOD_INCLUDE_DIRS)
MARK_AS_ADVANCED(LIMESDRMOD_LIBRARIES LIMESDRMOD_INCLUDE_DIRS)

